version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    volumes:
      - .:/app
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
